spring:
  application:
    name: PostProject

  datasource:
    url: jdbc:mariadb://localhost:3306/post_project
    username: root
    password: qwe123
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  type-aliases-package: com.example.postproject
  mapper-locations: classpath:mapper/*.xml